### ISSUE TITLE
Exported resource collector

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#126]
AFAIK the `puppetresources` command line does not show collected exported resources. There are there on the declaration side but not on the collector side.

Is there a way to enable such a feature ?

**Comment by bartavelle** [comment]
I don't understand the issue. In this example:

    node 'a.b' { 
      @@file { '/tmp/exported':
        ensure => present;
      } 
    
      File<<| |>>
    }

Should output this:

    file {
      <@@>/tmp/exported: # "/tmp/x/manifests/site.pp" (line 2, column 12) a.b [Scope []]
        ensure  => present,
        group   => root,
        mode    => 0644,
        path    => /tmp/exported,
        require => Class[::];
    }
    stage {
      main: # "dummy" (line 1, column 1) a.b [Scope []]
        ;
    }
     Exported: 
    file {
      <@@>/tmp/exported: # "/tmp/x/manifests/site.pp" (line 2, column 12) a.b [Scope []]
        ensure  => present,
        require => Class[::];
    }

Here `<@@>` means "exported and realized", whereas `@@` just means exported.

**Comment by PierreR** [comment]
I am trying to do something alike 

```
puppetresources -p . -a node1,node2 --hiera ./tests/hiera.yaml --pdbfile ./tests/facts.yaml --checkExported
```
The first node declares exporting resources and the second collect them.

**Comment by bartavelle** [comment]
IIRC it should be seen on the "source" part (the commented part) that this comes from another node.

**Comment by PierreR** [comment]
@bartavelle I was reviewing this issue to eventually close it. But I still wonder how I can emulate an exported resources faking the puppetdb state with a local `pdbfile`.  Here is a try given both the exported resources from the declaration side (salmaster.prod) and the collect side (pgserver.prod):
```
facts:
  pgserver.prod:
    role: pgserver
    zone: prod
    environment: middleware_prod
  saltmaster.prod:
    role: saltmaster
    zone: prod
    environment: middleware_prod
resources:
  pgserver.prod:
    data:
      resources:
        - aliases: []
          sourceline: 1
          parameters:
            require: Class[application::profile::postgrest::install]
            db_host: pgserver-cicd.prd.srv.cirb.lan
            db_user: salt
            db_name: saltstack
            port: 3000
          exported: false
          title: postgrest for saltstack
          type: application::profile::postgrest::service
          sourcefile: 'null'
          tags:
          - application::role::pgserver
          - application
          - service
          - node
          - default
          - application::profile::postgrest::service
          - profile
          - role
          - postgrest
          - pgserver
          - application::profile::pgserver
          - class
  salt-master.prod:
    data:
      resources:
        - aliases: []
          sourceline: 1
          parameters:
            require: Class[application::profile::postgrest::install]
            db_host: pgserver-cicd.prd.srv.cirb.lan
            db_user: salt
            db_name: saltstack
            port: 3000
          exported: true
          title: postgrest for saltstack
          type: application::profile::postgrest::service
          sourcefile: 'null'
          tags:
          - application::profile::saltmaster
          - application
          - service
          - node
          - default
          - application::profile::postgrest::service
          - profile
          - role
          - postgrest
          - application::role::saltmaster
          - saltmaster
          - class
```
I would like to see realized exported resources with:
`puppetresources -p . -o pgserver.prod --hiera ./tests/hiera.yaml --pdbfile ./tests/facts.yaml` but I don't see any mention of them.
The manifest/site.pp looks like this:
```
node default {
	$node_subgroup = pick($::subgroup, ' ')

  if $::role != undef {
    if $::subgroup != undef {
      $role_path =  "${::subgroup}::${::role}"
    } else {
      $role_path = "${::role}"
    }
    include "application::role::${role_path}"
  } else {
    include ::profile::cirb
  }
}

```
Someone on the `pgserver` catalog there is this line:
```  
Application::Profile::Postgrest::Service <<| |>>
```
