### ISSUE TITLE
pdb: common facts

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#5]
This is actually a feature request.

I am not sure if this is possible yet but I would like to have the generated pbdfile to have a section for common facts. Something like:

```
facts:
  common:
    operatingsystem: CentOS
  svappcavl227:
    memorysize: 1.76 GB
    ipaddress: 192.168.0.2
    hostname: svappc
      .
      .
      .

```

I have also realized that if I mess up with the generated yaml file, the fact section might get deleted completely by the run of `puppetresource`.
